// <auto-generated />
using System;
using ExamenIntra;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ExamenIntra.Migrations
{
    [DbContext(typeof(ExamenIntraContext))]
    [Migration("20210318151559_AjoutBaseDeDonnees")]
    partial class AjoutBaseDeDonnees
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ExamenIntra.partieLinq.Fruit", b =>
                {
                    b.Property<int>("FruitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PersonneId")
                        .HasColumnType("int");

                    b.HasKey("FruitId");

                    b.HasIndex("PersonneId");

                    b.ToTable("Fruits");
                });

            modelBuilder.Entity("ExamenIntra.partieLinq.Personne", b =>
                {
                    b.Property<int>("PersonneId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Genre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PersonneId");

                    b.ToTable("Personnes");
                });

            modelBuilder.Entity("ExamenIntra.partieLinq.Fruit", b =>
                {
                    b.HasOne("ExamenIntra.partieLinq.Personne", null)
                        .WithMany("FruitsAimes")
                        .HasForeignKey("PersonneId");
                });

            modelBuilder.Entity("ExamenIntra.partieLinq.Personne", b =>
                {
                    b.Navigation("FruitsAimes");
                });
#pragma warning restore 612, 618
        }
    }
}
